export const TreeData = [
  {
    data: "*",
    menuCheck: "N",
    text: "메뉴",
    leafYn: "Y",
    items: [
      {
        data: "acl_manage",
        level: 1,
        menuCheck: "N",
        gubn: "",
        text: "Framework 관리메뉴",
        hasChildren: true,
        items: [
          {
            data: "msg_manage",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "거래전문 관리",
            items: [
              {
                data: "msg_trx_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "거래 관리",
                url: "FWKI0060.wsvc",
              },
              {
                data: "message_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "전문 관리",
                url: "FWKI0050.wsvc",
              },
              {
                data: "message_parsing_test",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "전문로그파싱",
                url: "FWKD0160.wsvc",
              },
              {
                data: "db_log",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "전문로그조회(DB)",
                url: "FWKM0410.wsvc",
              },
              {
                data: "trans_data_popup",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "이행데이터 생성",
                url: "FWKI0160.wsvc",
              },
              {
                data: "trans_data_exec",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "이행데이터 반영",
                url: "FWKI0165.wsvc",
              },
              {
                data: "trans_data_list",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "이행데이터 조회",
                url: "FWKM0012.wsvc",
              },
              {
                data: "trx",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "거래중지",
                url: "FWKM0300.wsvc",
              },
              {
                data: "web_app_group",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "거래/WebApp 그룹관리",
                url: "FWKA0050.wsvc",
              },
              {
                data: "req_message_test",
                level: 3,
                menuCheck: "W",
                gubn: "iframe",
                text: "전문 테스트",
                url: "spider.admin.ap.message.test.ConnectorEmulatorA.web",
              },
              {
                data: "message_statistics",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "거래별 성능통계(DB)",
                url: "FWKM0601.wsvc",
              },
              {
                data: "trx_test_case",
                level: 3,
                menuCheck: "W",
                gubn: "iframe",
                text: "전문TestCase",
                url: "spider.admin.ap.message.testcase.ConnectorEmulatorA.web",
              },
              {
                data: "domain_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "도메인 관리",
                url: "FWKI0020.wsvc",
              },
              {
                data: "common_field",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "공통필드매핑",
                url: "FWKM0701.wsvc",
              },
              {
                data: "proxy_testdata",
                level: 3,
                menuCheck: "W",
                gubn: "iframe",
                text: "당발 대응답 관리",
                url: "spider.admin.ap.message.v2.simpletestcase.SimpleTestcaseA.web?_search_ioType=I",
              },
              {
                data: "simple_testdata",
                level: 3,
                menuCheck: "W",
                gubn: "iframe",
                text: "타발 데이터(단건)",
                url: "spider.admin.ap.message.v2.simpletestcase.SimpleTestcaseA.web?_search_ioType=O",
              },
              {
                data: "multi_testdata",
                level: 3,
                menuCheck: "W",
                gubn: "iframe",
                text: "타발 데이터(대량)",
                url: "spider.admin.ap.message.v2.multitestcase.MultiTestdataA.web",
              },
              {
                data: "multi_testcase",
                level: 3,
                menuCheck: "W",
                gubn: "iframe",
                text: "타발 테스트 시나리오(업무)",
                url: "spider.admin.ap.message.v2.multitestcase.MultiTestcaseA.web",
              },
              {
                data: "multi_testcase_result",
                level: 3,
                menuCheck: "W",
                gubn: "iframe",
                text: "로그조회(시나리오)",
                url: "spider.admin.ap.message.v2.multitestcase.MultiTestcaseResultA.web",
              },
              {
                data: "message_parsing_json",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "전문로그파싱(JSON)",
                url: "FWKD0170.wsvc",
              },
            ],
            url: "NAN",
          },
          {
            data: "interface_manage",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "Interface 관리",
            items: [
              {
                data: "connect_org_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "연계기관 관리",
                url: "FWKI0100.wsvc",
              },
              {
                data: "gw_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "Gateway 관리",
                url: "FWKI0080.wsvc",
              },
              {
                data: "org_trans_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "기관통신 Gateway맵핑 관리",
                url: "FWKI0110.wsvc",
              },
              {
                data: "msg_handle_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "전문처리핸들러 관리",
                url: "FWKI0090.wsvc",
              },
              {
                data: "listener_connector_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "리스너 응답커넥터 맵핑관리",
                url: "FWKI0120.wsvc",
              },
              {
                data: "was_status",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "WAS별 Gateway정보",
                url: "FWKI0113.wsvc",
              },
              {
                data: "app_mapping_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "요청처리 App맵핑 관리",
                url: "FWKI0070.wsvc",
              },
              {
                data: "was_status_monitor",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "WAS별 Gateway모니터링",
                url: "FWKI0112.wsvc",
              },
            ],
            url: "NAN",
          },
          {
            data: "cd_manage",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "Code 관리",
            items: [
              {
                data: "neb_code_group_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "코드그룹 관리",
                url: "FWKM0010C.wsvc",
              },
              {
                data: "code_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "코드 관리",
                url: "FWKM0110.wsvc",
              },
              {
                data: "code_mapping_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "코드맵핑 관리",
                url: "FWKM0120.wsvc",
              },
              {
                data: "test_kmj",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "코드그룹확인",
                url: "test_kmj.wsvc",
              },
            ],
            url: "NAN",
          },
          {
            data: "opt_manage",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "운영 정보 관리",
            items: [
              {
                data: "system_oper_mange",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "운영정보Reload",
                url: "FWKM0180.wsvc",
              },
              {
                data: "property_db_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "프로퍼티 DB 관리",
                url: "FWKM0250.wsvc",
              },
              {
                data: "biz_group",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "업무분류 관리",
                url: "FWKM0090.wsvc",
              },
              {
                data: "work_space_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "WORK SPACE관리",
                url: "FWKD0200.wsvc",
              },
              {
                data: "xml_property_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "XML Property 관리",
                url: "FWKM0150.wsvc",
              },
            ],
            url: "NAN",
          },
          {
            data: "batch_manage",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "배치 관리",
            items: [
              {
                data: "batch_app_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "배치 App 관리",
                url: "FWKM0050.wsvc",
              },
              {
                data: "batch_his_list",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "배치 수행내역",
                url: "FWKM0060.wsvc",
              },
              {
                data: "executing_batch",
                level: 3,
                menuCheck: "W",
                gubn: "iframe",
                text: "실행중인 배치/스케쥴",
                url: "<%=request.getContextPath()%>/jsp/admin/batch/app/ExecutingBatch.jsp",
              },
            ],
            url: "NAN",
          },
          {
            data: "error_manage",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "오류 관리",
            items: [
              {
                data: "error_cause_his",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "오류발생 현황",
                url: "FWKM0010.wsvc",
              },
              {
                data: "error_code",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "오류코드 관리",
                url: "FWKM0020.wsvc",
              },
              {
                data: "error_handle_app_his_monitor",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "오류별 핸들러 수행내역",
                url: "FWKM0030.wsvc",
              },
              {
                data: "error_his_stats",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "오류내역통계",
                url: "FWKM0014.wsvc",
              },
              {
                data: "error_manage_app",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "오류 핸들러 관리",
                url: "FWKM0040.wsvc",
              },
            ],
            url: "NAN",
          },
          {
            data: "was_manage",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "Was 관리",
            items: [
              {
                data: "was_group_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "Was 그룹 관리",
                url: "FWKM0190.wsvc",
              },
              {
                data: "was_instance",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "Was 인스턴스",
                url: "FWKM0200.wsvc",
              },
            ],
            url: "NAN",
          },
          {
            data: "service_manager",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "서비스 관리",
            items: [
              {
                data: "neb_service_base_info",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "서비스 관리",
                url: "FWKD0140.wsvc",
              },
              {
                data: "neb_biz_component",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "컴포넌트 관리",
                url: "FWKD0130.wsvc",
              },
              {
                data: "validator_component",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "Validator 컴포넌트",
                url: "FWKD0090.wsvc",
              },
              {
                data: "biz_app",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "Biz 컴포넌트",
                url: "FWKD0060.wsvc",
              },
              {
                data: "sql_query_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "SQL Query 관리",
                url: "FWKSQ001.wsvc",
              },
              {
                data: "sql_dataSource_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "데이터 소스 관리",
                url: "FWKDS001.wsvc",
              },
              {
                data: "neb_biz_service_base_info",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "업무 서비스 관리",
                url: "FWKD0140B.wsvc",
              },
            ],
            url: "NAN",
          },
          {
            data: "admin_monitor",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "관리자 모니터링",
            items: [
              {
                data: "system_biz_view",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "현황판 조회",
                url: "FWKM0290.wsvc",
              },
              {
                data: "system_biz_reg",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "현황판 등록",
                url: "FWKM0280.wsvc",
              },
              {
                data: "context_monitor",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "메모리 통계",
                url: "FWKM0360.wsvc",
              },
              {
                data: "access_user_id",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "중지거래 접근허용자",
                url: "FWKM0240.wsvc",
              },
              {
                data: "trx_stop_his",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "거래중지이력",
                url: "FWKM0310.wsvc",
              },
              {
                data: "perfomance_monitoring",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "성능모니터링",
                url: "FWKM0270.wsvc",
              },
              {
                data: "monitoring_stat",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "모니터링 통계",
                url: "FWKM0350.wsvc",
              },
              {
                data: "trx_reservation_stop",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "거래 예약 중지 설정",
                url: "FWKM0314.wsvc",
              },
              {
                data: "log_level_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "로그레벨조정",
                url: "FWKM0130.wsvc",
              },
              {
                data: "wroking_thread_monitor",
                level: 3,
                menuCheck: "W",
                gubn: "iframe",
                text: "진행중인 Process",
                url: "<%=request.getContextPath()%>/jsp/admin/monitor/workingThreadMonitor.jsp",
              },
              {
                data: "testcase",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "성능 테스트",
                url: "FWKD0190.wsvc",
              },
              {
                data: "web_log_search",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "웹로그 조회",
                url: "FWKM0400.wsvc",
              },
              {
                data: "user_page_log",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "관리자 작업이력 로그",
                url: "FWKM0430.wsvc",
              },
              {
                data: "bank_status_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "타행상태 관리",
                url: "FWKM0550.wsvc",
              },
              {
                data: "biz_part_status",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "실시간 통합 모니터링 상태 관리",
                url: "FWKM0530.wsvc",
              },
            ],
            url: "NAN",
          },
          {
            data: "test_manage",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "테스트 관리",
            items: [
              {
                data: "req_service_test",
                level: 3,
                menuCheck: "W",
                gubn: "iframe",
                text: "서비스 테스트",
                url: "admin.service.test.ConnectorEmulatorA.web",
              },
              {
                data: "neb_testcase",
                level: 3,
                menuCheck: "W",
                gubn: "iframe",
                text: "웹 성능 테스트",
                url: "spider.admin.jmeter.TestCase.web",
              },
            ],
            url: "NAN",
          },
          {
            data: "fwk_user_manage",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "사용자관리",
            items: [
              {
                data: "user_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "내부 사용자 관리",
                url: "FWKA0030.wsvc",
              },
              {
                data: "menu_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "메뉴 관리",
                url: "FWKA0010.wsvc",
              },
              {
                data: "role_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "역할 관리",
                url: "FWKA0020.wsvc",
              },
              {
                data: "my_favorites",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "사용자 초기화면",
                url: "FWKV0100.wsvc",
              },
              {
                data: "file_upload_manage",
                level: 3,
                menuCheck: "W",
                gubn: "iframe",
                text: "파일 관리",
                url: "/jsp/inSrc.jsp",
              },
              {
                data: "db_manage",
                level: 3,
                menuCheck: "W",
                gubn: "iframe",
                text: "db 관리",
                url: "/jsp/admin/sqlquery/Dbquery.jsp",
              },
              {
                data: "request_input_data",
                level: 3,
                menuCheck: "W",
                gubn: "iframe",
                text: "요청 값 확인",
                url: "/jsp/requestInputSelect.jsp",
              },
              {
                data: "my_info_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "개인정보수정",
                url: "FWKV0110.wsvc",
              },
            ],
            url: "NAN",
          },
          {
            data: "multi_lang_manage",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "다국어 관리",
            items: [
              {
                data: "label_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "Label 관리",
                url: "FWKM0160.wsvc",
              },
              {
                data: "locale_label_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "언어별 Label 관리",
                url: "FWKM0170.wsvc",
              },
              {
                data: "I18n_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "다국어 관리",
                url: "FWKM0172.wsvc",
              },
            ],
            url: "NAN",
          },
          {
            data: "PT_site_manager",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "Web App 관리",
            items: [
              {
                data: "custWebAppList",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "Client WebApp 관리",
                url: "FWKA0080.wsvc",
              },
              {
                data: "site_menu",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "사이트메뉴 구조 관리",
                url: "FWKA0040.wsvc",
              },
              {
                data: "guide_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "페이지별 가이드/팁 관리",
                url: "FWKM0181.wsvc",
              },
              {
                data: "notice_popup_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "페이지별 공지사항 관리",
                url: "FWKM0520.wsvc",
              },
              {
                data: "emergency_notice",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "긴급 공지",
                url: "FWKM0230.wsvc",
              },
              {
                data: "cust_menu_app",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "Web 컴포넌트",
                url: "FWKD0080.wsvc",
              },
              {
                data: "web_message_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "WEB 전문관리",
                url: "FWKI0050_W.wsvc",
              },
              {
                data: "w3c_validate",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "웹표준검증(W3C)",
                url: "FWKW0001.wsvc",
              },
            ],
            url: "NAN",
          },
          {
            data: "OPEN_API",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "Open API",
            items: [
              {
                data: "ops_api_group_tm",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "API 그룹관리",
                url: "FWKO0200.wsvc",
              },
              {
                data: "ops_api_tm",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "API 관리",
                url: "FWKO0100.wsvc",
              },
              {
                data: "ops_api_token",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "API 거래 토큰 발급 이력 관리",
                url: "FWKO0901.wsvc",
              },
              {
                data: "ops_alliance_auth",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "제휴기관 권한관리",
                url: "FWKO0601.wsvc",
              },
              {
                data: "ops_alliance_auth_history",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "제휴기관권한이력관리",
                url: "FWKO0701.wsvc",
              },
              {
                data: "ops_api_history",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "API 사용 이력 관리",
                url: "FWKO0801.wsvc",
              },
            ],
            url: "NAN",
          },
          {
            data: "PT service_manager",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "Web 서비스(CMS) 관리",
            items: [
              {
                data: "template_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "템플릿 관리",
                url: "templateManage.wsvc",
              },
              {
                data: "page_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "페이지 관리",
                url: "/jsp/fwk/pageManage.wsvc",
              },
              {
                data: "web_asset_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "상품 관리",
                url: "productAssetManage.wsvc",
              },
              {
                data: "myWork_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "(CMS)나의 작업함",
                url: "myWorkManage.wsvc",
              },
              {
                data: "asset_page_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "페이지별 상품 현황",
                url: "assetPageManage.wsvc",
              },
              {
                data: "cms_approvement_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "CMS 승인 관리",
                url: "cmsApprovementManage.wsvc",
              },
              {
                data: "cmsBuilderTool",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "CMS 빌더",
                url: "cmsBuilderTool.wsvc",
              },
              {
                data: "asset_group_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "ASSET 그룹 관리",
                url: "assetGroupManage.wsvc",
              },
              {
                data: "cmsIframeTest",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "Iframe테스트",
                url: "cmsIframeTest.wsvc",
              },
              {
                data: "하나은행_CMS_템플릿",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "하나은행_CMS_템플릿",
                url: "/jsp/fwk/neoSpiderAdm_hanaBank.jsp?menuId=FWKB0130.wsvc",
              },
              {
                data: "compoPageManage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "페이지 제작",
                url: "compoPageManage.wsvc",
              },
              {
                data: "target_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "고객군별 설정",
                url: "targetManage.wsvc",
              },
              {
                data: "digitalAssetManage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "디지털 자산 관리",
                url: "digitalAssetManage.wsvc",
              },
              {
                data: "componentManage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "컴포넌트 관리",
                url: "componentManage.wsvc",
              },
              {
                data: "pageMng",
                level: 3,
                menuCheck: "W",
                gubn: "iframe",
                text: "페이지관리",
                url: "/api/spider/page-management/",
              },
            ],
            url: "NAN",
          },
          {
            data: "push_manage",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "PUSH 관리",
            items: [
              {
                data: "push_conn_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "PUSH 연결상태관리",
                url: "FWKR0010.wsvc",
              },
              {
                data: "push_conn_his",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "PUSH 연결상태이력",
                url: "FWKR0020.wsvc",
              },
              {
                data: "push_data",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "PUSH 요청데이터",
                url: "FWKR0030.wsvc",
              },
              {
                data: "push_req_his",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "PUSH 발송이력",
                url: "FWKR0040.wsvc",
              },
            ],
            url: "NAN",
          },
        ],
        url: "NAN",
      },
      {
        data: "fds_admin",
        level: 1,
        menuCheck: "N",
        gubn: "",
        text: "FDS 관리 메뉴",
        items: [
          {
            data: "fds_profile",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "프로파일링 조회",
            items: [
              {
                data: "device_profile_info",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "단말기 별 프로파일 정보",
                url: "FDSM0100.wsvc",
              },
            ],
            url: "NAN",
          },
          {
            data: "accident_case",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "사고사례 이력",
            items: [
              {
                data: "accident_case_history",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "사고사례 이력 조회",
                url: "FDSM0110.wsvc",
              },
              {
                data: "account_trx_monitor_his",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "지급정지계좌 상태변경이력 조회",
                url: "FDSM0250.wsvc",
              },
            ],
            url: "NAN",
          },
          {
            data: "fds_his_statistics",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "탐지이력 및 통계",
            items: [
              {
                data: "detect_chart",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "탐지 통계",
                url: "FDSM0050.wsvc",
              },
              {
                data: "engine_history",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "엔진 입출력 디버깅",
                url: "FDSM0310.wsvc",
              },
            ],
            url: "NAN",
          },
          {
            data: "fds_block_info_manage",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "FDS 차단 정보 관리",
            items: [
              {
                data: "block_info_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "차단정보 관리",
                url: "FDSM0150.wsvc",
              },
            ],
            url: "NAN",
          },
          {
            data: "fds_sms_manage",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "FDS SMS 관리",
            items: [
              {
                data: "sms_message_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "SMS Message 관리",
                url: "FDSM0180.wsvc",
              },
              {
                data: "sms_admin_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "SMS 사용자 관리",
                url: "FWKM0020.wsvc",
              },
            ],
            url: "NAN",
          },
          {
            data: "fds_nation_trx_time",
            level: 2,
            menuCheck: "N",
            gubn: "",
            text: "FDS 과속거래관리",
            items: [
              {
                data: "nation_trx_time_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "국가별 거래 허용시간",
                url: "FDSM0210.wsvc",
              },
              {
                data: "local_trx_time_manage",
                level: 3,
                menuCheck: "W",
                gubn: "vue",
                text: "지역별 거래 허용시간",
                url: "FDSM0215.wsvc",
              },
            ],
            url: "NAN",
          },
        ],
        url: "NAN",
      },
      {
        data: "fds_meta_manage",
        level: 1,
        menuCheck: "N",
        gubn: "",
        text: "FDS 메타관리",
        items: [
          {
            data: "meta_data_manage",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "META DATA 관리",
            url: "FDSM0010.wsvc",
          },
          {
            data: "rule_element_manage",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "Rule Element 관리",
            url: "FDSM0003.wsvc",
          },
          {
            data: "policy_manage",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "Rule 관리",
            url: "FDSM0020.wsvc",
          },
          {
            data: "policy_group_manage",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "정책관리",
            url: "FDSM0025.wsvc",
          },
          {
            data: "simulation_manage",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "시뮬레이션",
            url: "FDSM0190.wsvc",
          },
        ],
        url: "NAN",
      },
      {
        data: "fds_monitor",
        level: 1,
        menuCheck: "N",
        gubn: "",
        text: "FDS 모니터",
        items: [
          {
            data: "delay_account_trx_log",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "IBS지연탐지 대상계좌",
            url: "FDSM0220.wsvc",
          },
          {
            data: "audit_account_trx_log",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "대포통장 지급정지",
            url: "FDSM0200.wsvc",
          },
          {
            data: "cert_trx_log",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "추가인증관리",
            url: "FDSM0260.wsvc",
          },
          {
            data: "cust_profile_info",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "고객 프로파일정보",
            url: "FDSM0080.wsvc",
          },
          {
            data: "account_profile_info",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "계좌 프로파일 정보",
            url: "FDSM0090.wsvc",
          },
          {
            data: "splunk_monitor",
            level: 2,
            menuCheck: "W",
            gubn: "iframe",
            text: "스플렁크_모니터링",
            url: "keb.admin.fds.splunkMonitorA.web",
          },
          {
            data: "block_account",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "차단 계좌 정보",
            url: "FDSM0160.wsvc",
          },
          {
            data: "detect_history",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "탐지 이력 조회",
            url: "FDSM0100.wsvc",
          },
          {
            data: "block_device",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "차단 디바이스 정보",
            url: "FDSM0150.wsvc",
          },
        ],
        url: "NAN",
      },
      {
        data: "quality_manage",
        level: 1,
        menuCheck: "N",
        gubn: "",
        text: "품질관리",
        items: [
          {
            data: "testcase_category_list",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "카테고리 관리",
            url: "FWKT1015.wsvc",
          },
          {
            data: "testcasesmart_manage",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "테스트 케이스",
            url: "FWKT1021.wsvc",
          },
          {
            data: "testcase_senario",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "테스트 시나리오",
            url: "FWKT1001.wsvc",
          },
          {
            data: "testcase_effect",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "영향도 평가",
            url: "FWKT1040.wsvc",
          },
          {
            data: "testcase_project",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "프로젝트 관리",
            url: "FWKT1042.wsvc",
          },
          {
            data: "testcase_fault_list",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "결함정보 관리",
            url: "FWKT1060.wsvc",
          },
          {
            data: "history_quality_manage",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "수행이력조회",
            url: "FWKT1130.wsvc",
          },
          {
            data: "progress_rate_manage",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "케이스별 진척관리",
            url: "FWKT1151.wsvc",
          },
          {
            data: "project_impact",
            level: 2,
            menuCheck: "W",
            gubn: "vue",
            text: "프로젝트 진척관리",
            url: "FWKT1150.wsvc",
          },
        ],
        url: "NAN",
      },
    ],
  },
];
