"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { TabProvider } from "@/providers/TabProvider";
import { Layout } from "@/components/shared/layout";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TabProvider>
          <Layout>{children}</Layout>
        </TabProvider>
      </body>
    </html>
  );
}
